---
- name: Generate an RSA key pair
  community.crypto.openssl_privatekey:
    path: "{{ key_file }}.pem"
    size: 2048
    type: RSA
  register: rsa_key_pair
  run_once: true

- name: Generate the public key from the private key
  ansible.builtin.shell:
    cmd: ssh-keygen -y -f "{{ key_file }}"
  register: ssh_key_gen_output


- name: Import the public key to AWS
  amazon.aws.ec2_key:
    name: "{{ key_name }}"
    key_material: "{{ lookup('file', key_file + '.pub') }}"
    region: "{{ region }}"
  register: ec2_key_result

- name: Launch Spot instance
  amazon.aws.ec2_instance:
    state: present
    key_name: "{{ key_name }}"
    instance_type: t2.micro
    image: ami-06e46074ae430fba6  # Amazon Linux 2 LTS AMI (HVM)
    wait: yes
    vpc_subnet_id: "{{ subnet.subnet.id }}"
    instance_tags:
      Name: GPT4All Instance
    spot_price: "0.0075"
    region: "us-east-1"
    aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
    instance_initiated_shutdown_behavior: terminate
  register: ec2

- name: Allocate a new Elastic IP
  amazon.aws.ec2_eip:
    region: "us-east-1"
    AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
  register: eip

- name: Associate the new Elastic IP with the instance
  amazon.aws.ec2_eip:
    region: "us-east-1"
    AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
    instance_id: "{{ ec2.instance_ids[0] }}"
    ip: "{{ eip.public_ip }}"
