---
- name: Request Spot instance
  amazon.aws.ec2_spot_instance:
    spot_price: "{{ spot_price }}"
    state: present
    wait: true
    wait_timeout: "{{ spot_wait_timeout }}"
    region: "{{ region }}"
    launch_specification:
      image_id: "{{ image_id }}"
      instance_type: "{{ instance_type }}"
      key_name: "{{ key_name }}"
      security_group_ids: ["{{ security_group_id }}"]
      subnet_id: "{{ vpc_subnet_id }}"
      block_device_mappings:
        - device_name: /dev/sda1
          ebs:
            volume_size: 8
            volume_type: gp2
            delete_on_termination: true
    tags:
      Name: "{{ instance_name }}"
  register: spot_instance

- name: Get instance ID from Spot instance request
  set_fact:
    instance_id: "{{ spot_instance.instance_id }}"

- name: Tag Spot instance
  amazon.aws.ec2_create_tags:
    resources: ["{{ instance_id }}"]
    tags:
      Name: "{{ instance_name }}"
    region: "{{ region }}"
    aws_profile: "{{ aws_profile }}"

- name: Allocate a new Elastic IP
  amazon.aws.ec2_allocate_address:
    domain: vpc
    region: "{{ region }}"
    aws_profile: "{{ aws_profile }}"
  register: eip

- name: Associate the new Elastic IP with the instance
  amazon.aws.ec2_associate_address:
    instance_id: "{{ instance_id }}"
    public_ip: "{{ eip.public_ip }}"
    region: "{{ region }}"
    aws_profile: "{{ aws_profile }}"
