---
- name: Generate an RSA key pair
  ansible.builtin.openssl_privatekey:
    path: "{{ key_file }}"
    type: RSA
    size: 2048
    mode: 0600
  register: private_key_result
  changed_when: private_key_result is changed

- name: Generate the public key from the private key
  ansible.builtin.shell:
    cmd: ssh-keygen -y -f "{{ key_file }}"
  register: ssh_key_gen_output

- name: Import the public key to AWS
  amazon.aws.ec2_key:
    name: "{{ key_name }}"
    key_material: "{{ lookup('file', key_file + '.pub') }}"
    region: "{{ region }}"
  register: ec2_key_result

- name: Request Spot instance
  amazon.aws.ec2_instance:
    key_name: "{{ key_name }}"
    instance_type: t2.micro
    image_id: ami-06e46074ae430fba6  # Amazon Linux 2 LTS AMI (HVM)
    wait: yes
    vpc_subnet_id: "{{ subnet.subnet.id }}"
    spot_price: "0.0075"
    region: "us-east-1"
    aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
    instance_initiated_shutdown_behavior: terminate
    launch_specification:
      InstanceMarketOptions:
        MarketType: 'spot'
        SpotOptions:
          MaxPrice: '0.0075'
  register: spot_request


- name: Get instance ID from Spot instance request
  set_fact:
    instance_id: "{{ spot_request.instances[0].instance_id }}"

- name: Tag Spot instance
  amazon.aws.ec2_instance:
    instance_ids: "{{ instance_id }}"
    tags:
      Name: GPT4All Instance
    region: "us-east-1"
    aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"



- name: Allocate a new Elastic IP
  amazon.aws.ec2_eip:
    region: "us-east-1"
    AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
  register: eip

- name: Associate the new Elastic IP with the instance
  amazon.aws.ec2_eip:
    region: "us-east-1"
    AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
    instance_id: "{{ spot_request.instance_id }}"
    ip: "{{ eip.public_ip }}"

