---
- name: Generate an RSA key pair
  ansible.builtin.openssh_keypair:
    path: "{{ playbook_dir }}/keypair_for_gpt4all"
    type: rsa
    size: 2048
  register: rsa_keypair

- name: Import the public key to AWS
  amazon.aws.ec2_key:
    name: "{{ key_name }}"
    key_material: "{{ lookup('file', playbook_dir + '/keys/id_rsa.pub') }}"
    state: present
  register: import_key_result

- name: Launch Spot instance
  amazon.aws.ec2_instance:
    state: present
    key_name: "{{ aws_keypair.key.name }}"
    instance_type: t2.micro
    image: ami-06e46074ae430fba6  # Amazon Linux 2 LTS AMI (HVM)
    wait: yes
    vpc_subnet_id: "{{ subnet.subnet.id }}"
    instance_tags:
      Name: GPT4All Instance
    spot_price: "0.0075"
    region: "us-east-1"
    aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
    instance_initiated_shutdown_behavior: terminate
  register: ec2

- name: Allocate a new Elastic IP
  amazon.aws.ec2_eip:
    region: "us-east-1"
    AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
  register: eip

- name: Associate the new Elastic IP with the instance
  amazon.aws.ec2_eip:
    region: "us-east-1"
    AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
    instance_id: "{{ ec2.instance_ids[0] }}"
    ip: "{{ eip.public_ip }}"
